# Generated by Django 4.2 on 2025-01-28 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default=datetime.datetime(2025, 1, 28, 13, 13, 3, 336007, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='token'),
            preserve_default=False,
        ),
    ]
